# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170303_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570'),
        ),
    ]
